theme: jekyll-theme-minimal
title: Vossian Antonomasia
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Gerardus_Johannes_Vossius_%281577-1649%29%2C_by_Anonymous.jpg/201px-Gerardus_Johannes_Vossius_%281577-1649%29%2C_by_Anonymous.jpg
description: Automatic extraction of Vossian Antonomasia from large newspaper corpora.

readme_index:
  remove_originals: true